public enum MusicScripting: String {
    case airplaydevice = "AirPlay device"
    case eqpreset = "EQ preset"
    case eqwindow = "EQ window"
    case urltrack = "URL track"
    case application = "application"
    case artwork = "artwork"
    case audiocdplaylist = "audio CD playlist"
    case audiocdtrack = "audio CD track"
    case browserwindow = "browser window"
    case encoder = "encoder"
    case filetrack = "file track"
    case folderplaylist = "folder playlist"
    case item = "item"
    case libraryplaylist = "library playlist"
    case miniplayerwindow = "miniplayer window"
    case playlistwindow = "playlist window"
    case playlist = "playlist"
    case radiotunerplaylist = "radio tuner playlist"
    case sharedtrack = "shared track"
    case source = "source"
    case subscriptionplaylist = "subscription playlist"
    case track = "track"
    case userplaylist = "user playlist"
    case videowindow = "video window"
    case visual = "visual"
    case window = "window"
}
